version: '3'
services:
  reverse-proxy:
    image: traefik
    command: --api.insecure=true --providers.docker --providers.docker.exposedByDefault=false
    restart: "no"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  microservice-HEX2RGB:
    build: microservice-HEX2RGB
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.microservice-HEX2RGB.rule=PathPrefix(`/microservice-HEX2RGB`)"
      - "traefik.http.routers.microservice-HEX2RGB.middlewares=microservice-HEX2RGB-stripprefix"
      - "traefik.http.middlewares.microservice-HEX2RGB-stripprefix.stripprefix.prefixes=/microservice-HEX2RGB"
      - "traefik.http.services.microservice-HEX2RGB.loadbalancer.server.port=3000"